---
title: "My career transition journey"
editor_options: 
  chunk_output_type: console
---

After reading some blog posts about other people's transition to data analytics and coding, I thought that it is worth to reflect on my own journey and share it in the first post on this blog.

Although I officially started to learn coding in R in 2022, my experience with analysing data to tell stories dates back as far as 2017.

------------------------------------------------------------------------

#### 1. Stepping into the world of data and statistics

I had always been fascinated with human behaviour, therefore deciding to study psychology was a natural choice for me.

While completing my undergraduate degree at Manchester Metropolitan University, I became a member of research club where I developed interest in using neuropsychological data to tell stories about one's emotional state.

During this degree, I also learnt the basics of statistics and how to generate first data insights using IBM SPSS. Despite enjoying using this software, I felt that managing larger data set was difficult and available data visualisations could have been improved. It was around 2018 when I first heard about R. However, being busy with university schedule and part-time work delayed digging into this topic further at the time.

#### 2. Even more data management

Fast forward to 2020, I completed my undergraduate degree just as the pandemic started and then worked remotely as a student advisor in a financial education company. In this role, I learnt data management using enterprise resource planning software, namely Microsoft Dynamics NAV, and advanced data management using Excel.

#### 3. Back in academia

In 2021, I started a master of science degree in clinical and health psychology at the University of Manchester. As I was completing it on a full-time basis, handling multiple, competing deadlines inspired me to look for ways to make working on my assignments more efficient and organised.
