project:
  type: website

website:
  page-navigation: true
  title: "Ewelina Stepien's blog"
  site-url: "https://estepien.netlify.app/"
  description: "I am a psychologist-turned-data analyst with a passion for making sense of data. This is my blog where I share the progress of my data analytics journey."
  page-footer:
    left: "Built with love and using Quarto (https://quarto.org)."
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/ewelina-stepien-959464257/
      - icon: github
        href: https://github.com/estepien1
      - icon: envelope
        href: mailto:e.stepien@icloud.com
  navbar:
    right:
      - about.qmd
      - text: Projects
        menu: 
          - text: All posts
            href: post/
      - text: Dark mode
format:
  html:
    smooth-scroll: true
    theme: 
      light: sketchy
      dark: darkly
    css: styles.css

editor: visual

comments:
  giscus:
    repo: estepien1/portfolio-blog