project:
  type: website

website:
  page-navigation: true
  title: "Ewelina Stepien's blog"
  site-url: "https://estepien.netlify.app/"
  repo-url: https://github.com/estepien1/portfolio-blog
  page-footer:
    left: "Built with love and using Quarto (https://quarto.org)."
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/ewelina-stepien-959464257/
      - icon: github
        href: https://github.com/estepien1
      - icon: envelope
        href: mailto:e.stepien@icloud.com
  navbar:
    right:
      - about.qmd
      # - text: Projects
      #   menu: 
      #     - text: All posts
      #       href: post/
format:
  html:
    theme: 
      light: minty
      dark: darkly
    css: styles.css
    smooth-scroll: true

editor: visual

comments:
  giscus:
    repo: estepien1/portfolio-blog